// This file is generated by nextjs-nango-plugin
// All logic is in the plugin - just wire up the routes
import { nangoHandler } from '@/lib/nango-config';

export const GET = nangoHandler.GET;
export const POST = nangoHandler.POST;
export const PUT = nangoHandler.PUT;
export const DELETE = nangoHandler.DELETE;
